### ISSUE TITLE
Etapa Industrial 1.1: Tela “despolpamento.cpp”

### ISSUE THREAD

**Issue by CamilaFerrer** [VinyPinheiro/EA_PIBIC#12]
Criar tela "despolpamento.cpp" e tela com a pergunta para essa atividade.

**Comment by VinyPinheiro** [comment]
Camila fiquei um pouco na duvida sobre a continuação deste. Dá uma olhada no meu ultimo commit pra ver se entendi certo. Se sim me explica como é a continuação
