### ISSUE TITLE
Tela com os logos das Tecnologias

### ISSUE THREAD

**Issue by VinyPinheiro** [VinyPinheiro/EA_PIBIC#3]

**Comment by edsomjr** [comment]
E também não vi esta tela dentre os arquivos.

**Comment by VinyPinheiro** [comment]
Acho q me confundi na hora que fiz o fechamento, ai fechei essa sem querer tambem, me desculpe

**Comment by VinyPinheiro** [comment]
Agora sim acho que está feito. Peço que deem uma olhada se era isso mesmo
